name: cricket_coach_app
description: "PS1 Cognix Cricket Coach App Frontend"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  connectivity_plus: ^6.0.3
  intl: ^0.19.0
  http: ^1.2.1
  file_picker: ^8.0.6
  logger: ^2.3.0
  camera: ^0.11.0+1
  path_provider: ^2.1.3
  video_player: ^2.9.1
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
